spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/mesu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
sspring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# borrar esto para activar el spring security
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# comentar esto para activar el spring security
# Configuracion para testeo con postman
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always